
title: Cafeteria Tematica
email: lcastaneda@tienda.com
description: >- # this means to ignore newlines until "baseurl:"
  Cafeteria Tematica es un lugar donde encontraras un ambiente calido
  donde podras disfrutar de los platos de la epoca de los 50.
baseurl: "/myNewSite" # the subpath of your site, e.g. /blog
url: "https://lhcastanedac.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LCC
github_username:  lhcastanedac

# Build settings
theme: minima
plugins:
  - jekyll-feed


text: Texto Nuevo

